### ISSUE TITLE
`jaxlib`: could not find a version that satisfies

### ISSUE THREAD

**Issue by mmikhasenko** [ComPWA/compwa-org#136]
## Bug description

the line
```
%pip install -q ampform==0.14.0 qrules==0.9.7 sympy==1.10.1 tensorwaves[jax,pwa]==0.4.5
```
causes the error
```
Note: you may need to restart the kernel to use updated packages.
ERROR: Could not find a version that satisfies the requirement jaxlib; extra == "jax" (from tensorwaves[jax,pwa]) (from versions: none)
ERROR: No matching distribution found for jaxlib; extra == "jax"
```
once I remove `jax` from the `tensorwaves` options, it works. 

## System info

I am on the `e73542d` commit of `polarization-sensitivity` branch running the notebook `017.ipynb`

Bug resulted on the following system:

- OS: Windows 10
- Python version: 3.8.13
- Virtual environment: `conda env create` from the project folder

**Comment by redeboer** [comment]
Seems that this is actually a problem in tensorwaves. In that case, you should have the same effect in the terminal:
```shell
conda env create --force  # completely reset the compwa-org environment
pip install tensorwaves[jax,pwa]==0.4.5
```
Note that tensorwaves etc is not part of the default dependencies defined for the Conda environment. They are installed once a notebook is run. The Conda config for this repo just installs dev tools like jupyter lab, pre-commit and sphinx.

https://github.com/ComPWA/compwa-org/blob/6501662070e2a5f24d01894a24052d9bc78634c0/setup.cfg#L39-L98

**Comment by redeboer** [comment]
My guess is that either jaxlib or TF (which comes in through `pwa`) is not supported on Windows

**Comment by redeboer** [comment]
88374c2 removes the need for TensorWaves. Only problem: have to think how to render phase space * intensity in the 1D intensity plots. Previously, those were just 1D histograms, but the Dalitz plot is now a meshgrid.

**Comment by redeboer** [comment]
> My guess is that either jaxlib or TF (which comes in through `pwa`) is not supported on Windows

See https://github.com/google/jax/issues/438. Since JAX is quite important in the notebooks, I recommend working with WSL2:
https://docs.microsoft.com/en-us/windows/wsl/install

**Comment by redeboer** [comment]
Did you get the numeric computations to work in WSL? If so, I'll close this issue.

**Comment by mmikhasenko** [comment]
no it works well with WLS

**Comment by redeboer** [comment]
Perfect!
